import React, {useState, useRef} from 'react';
import {defaultFilters} from './discoverFilters.js';
export default function DiscoverFilters({filters, setFilters, locate, locating, locationMessage, hasLocation, types}) {
  const controls = useRef(null);
  const [panel,setPanel] = useState(null);
  const [draft,setDraft] = useState(filters);
  const update = patch => setFilters(f=>({...f,...patch}));
  const days = Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return {key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,label:i===0?'Today':d.toLocaleDateString('en-GB',{weekday:'short'}),day:d.getDate()};});
  const toggle = name => {controls.current?.scrollIntoView({block:'start'});setDraft(filters);setPanel(panel===name?null:name);};
  return <div className="discover-controls" ref={controls} onKeyDown={e=>{if(e.key==='Escape')setPanel(null);}}>
    <label className="discover-search"><span className="sr-only">Search sessions, clubs or venues</span><input type="search" placeholder="Search sessions, clubs or venues" value={filters.query} onChange={e=>update({query:e.target.value})}/></label>
    <div className="discover-dates" aria-label="Session date"><button aria-pressed={filters.date==='any'} onClick={()=>update({date:'any'})}>All<span>dates</span></button>{days.map(d=><button key={d.key} aria-pressed={filters.date===d.key} onClick={()=>update({date:d.key})}>{d.label}<span>{d.day}</span></button>)}</div>
    <div className="discover-filterbar">{[['sort',filters.sort==='distance'?'Nearest first':filters.sort==='time'?'Soonest first':'Smart sort'],['nearby',filters.radius==='any'?'All areas':`${filters.radius} km`],['filters','Filters']].map(([key,label])=><button key={key} aria-expanded={panel===key} aria-controls="discover-filter-panel" onClick={()=>toggle(key)}>{label} <span>{panel===key?'▴':'▾'}</span></button>)}</div>
    {panel && <><button className="discover-backdrop" aria-label="Close filters" onClick={()=>setPanel(null)}/><div className="discover-panel" id="discover-filter-panel">
      {panel==='sort' && ['smart','distance','time'].map((s,i)=><button className="discover-option" key={s} aria-pressed={filters.sort===s} onClick={()=>{if(s==='distance'&&!hasLocation)locate();update({sort:s});setPanel(null);}}>{['Smart sort','Nearest first','Soonest first'][i]}</button>)}
      {panel==='nearby' && <><button className="location-button" disabled={locating} onClick={locate}>{locating?'Locating…':hasLocation?'Refresh my location':'Use my location'}</button><div className="nearby-options"><span>Nearby</span><div>{['any',0.5,1,2,3,5,10].map(r=><button className="discover-option" key={r} aria-pressed={filters.radius===r} onClick={()=>{if(r!=='any'&&!hasLocation)locate();update({radius:r});setPanel(null);}}>{r==='any'?'All areas':r===0.5?'500 m':`${r} km`}</button>)}</div></div></>}
      {panel==='filters' && <><label>Session start time</label><div className="time-inputs"><input aria-label="Start time" type="time" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/><span>–</span><input aria-label="End time" type="time" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></div><div className="time-presets">{[0,6,12,18].map(h=><button key={h} aria-pressed={draft.start===`${String(h).padStart(2,'0')}:00`&&draft.end===(h===18?'':`${String(h+6).padStart(2,'0')}:00`)} onClick={()=>setDraft({...draft,start:`${String(h).padStart(2,'0')}:00`,end:h===18?'':`${String(h+6).padStart(2,'0')}:00`})}>{h}–{h+6}</button>)}</div><div className="filter-selects"><label>Event type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{types.map(t=><option key={t} value={t}>{t==='any'?'Any type':t}</option>)}</select></label><label>Level<select value={draft.level} onChange={e=>setDraft({...draft,level:e.target.value})}><option value="any">Any level</option><option value="1-3">Beginner L1–L3</option><option value="3-6">Club L3–L6</option><option value="6-9">Advanced L6–L9</option></select></label></div><p>Free sessions</p><div className="time-presets">{[false,true].map(free=><button key={String(free)} aria-pressed={draft.free===free} onClick={()=>setDraft({...draft,free})}>{free?'Free only':'All'}</button>)}</div>{draft.start&&draft.end&&draft.start>=draft.end&&<p role="alert">End time must be later than start time.</p>}<div className="filter-actions"><button onClick={()=>{setDraft({...defaultFilters});setFilters({...defaultFilters});}}>Reset</button><button disabled={Boolean(draft.start&&draft.end&&draft.start>=draft.end)} onClick={()=>{setFilters(draft);setPanel(null);}}>Apply</button></div></>}
    </div></>}
    <div className="location-status"><button disabled={locating} onClick={locate}>{locating?'Locating…':hasLocation?'Location enabled':'Use my location'}</button><span role="status">{locationMessage}</span></div>
  </div>;
}
