import React, {useEffect,useRef,useState} from 'react';
import {Wallet,ClipboardList,Megaphone,Send,Grid2X2,ShoppingBag,BarChart3,SlidersHorizontal,Settings,X,ArrowLeft} from 'lucide-react';
import './myspace.css';
const primary=[['wallet','My Wallet',Wallet],['orders','My Orders',ClipboardList],['promotion','My Promotions',Megaphone],['recommend','Recommend Jimmi',Send],['more','More Features',Grid2X2]];
export default function MySpaceTools({bookings,sessions,stats,openAccountModal,go}) {
 const [page,setPage]=useState(null),[tab,setTab]=useState('Wallet details'),[orderKind,setOrderKind]=useState('Venue orders'),[orderStatus,setOrderStatus]=useState('All orders'),[message,setMessage]=useState('');
 const dialog=useRef(null);
 useEffect(()=>{if(page&&!dialog.current.open)dialog.current.showModal();if(!page&&dialog.current?.open)dialog.current.close();},[page]);
 const open=p=>{setPage(p);setMessage('');};
 const titles={wallet:'My Wallet',orders:'My Orders',promotion:'My Promotions',recommend:'Recommend Jimmi',more:'More Features',shop:'Jimmi Shop',activity:'Activity Data'};
 const settings=()=>{setPage(null);openAccountModal('settings');};
 return <><section className="space-shortcuts" aria-label="My Space tools">{primary.map(([id,label,Icon])=><button key={id} onClick={()=>open(id)}><span><Icon size={25}/></span>{label}</button>)}</section>
 <dialog ref={dialog} className={`space-dialog ${page==='more'?'space-sheet':''}`} onCancel={()=>setPage(null)} onClick={e=>{if(e.target===dialog.current)setPage(null);}}><div className="space-content" onClick={e=>e.stopPropagation()}><header><button aria-label="Back to My Space" onClick={()=>setPage(null)}><ArrowLeft size={20}/></button><h2>{titles[page]}</h2><button aria-label="Close" onClick={()=>setPage(null)}><X size={20}/></button></header>
 {page==='more'&&<><h3>Frequently used</h3><div className="space-more-grid">{[...primary.slice(0,4),['shop','Jimmi Shop',ShoppingBag]].map(([id,label,Icon])=><button key={id} onClick={()=>open(id)}><Icon size={24}/>{label}</button>)}</div><h3>Data &amp; settings</h3><div className="space-more-grid"><button onClick={()=>open('activity')}><BarChart3 size={24}/>Activity Data</button><button onClick={settings}><SlidersHorizontal size={24}/>Preferences</button><button onClick={settings}><Settings size={24}/>Platform Settings</button></div></>}
 {page==='wallet'&&<><div className="space-wallet"><div className="space-balance"><div>Total balance<strong>£ —</strong></div><div>Jimmi Point<strong>—</strong></div></div><div className="space-balance"><div>Frozen funds <button onClick={()=>setMessage('Frozen-fund details will be available when your wallet is connected.')}>View details ›</button><strong>£ —</strong></div><div>Available to withdraw<strong>£ —</strong></div></div><div className="space-actions"><button disabled>Withdraw</button><button disabled>Top up</button></div><p>Wallet and Jimmi Point are not connected yet. Balances are unavailable; top-ups and withdrawals are not enabled.</p></div><div className="space-tabs">{['Wallet details','Activity reconciliation'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="space-filters"><label>Month<input type="month"/></label><label>Entry type<select><option>All types</option><option>Top-up</option><option>Withdrawal</option><option>Session payment</option><option>Refund</option><option>Jimmi Point</option></select></label></div><p className="space-empty">{tab==='Wallet details'?'Wallet transactions are not available yet.':'Activity reconciliation is not available yet.'}</p></>}
 {page==='orders'&&<><div className="space-tabs">{['Venue orders','Promotion orders'].map(t=><button key={t} aria-pressed={orderKind===t} onClick={()=>setOrderKind(t)}>{t}</button>)}</div><div className="space-tabs space-order-status">{['All orders','To use','Used / To review','Refunds / After-sales'].map(t=><button key={t} aria-pressed={orderStatus===t} onClick={()=>setOrderStatus(t)}>{t}</button>)}</div><p className="space-note">Preview bookings only. Live orders are not connected.</p>{orderKind==='Venue orders'&&['All orders','To use'].includes(orderStatus)&&bookings.length?bookings.map(b=>{const s=sessions.find(s=>s.id===b.id);return s?<button className="space-order" key={b.id} onClick={()=>{setPage(null);go('eventDetail',{eventId:b.id});}}><strong>{s.name}</strong><span>{s.date} · {s.timeStart}</span><span>Preview booking · £{s.price}</span></button>:null;}):<p className="space-empty">{orderKind==='Promotion orders'?'Promotion orders are not available yet.':'No orders in this category.'}</p>}</>}
 {page==='promotion'&&<><h3>Your promotions</h3><p className="space-empty">Your promotion links, referrals and earnings will appear here once the promotion programme launches.</p><p>No promotion or commission tracking is active yet.</p></>}
 {page==='recommend'&&<><h3>More friends. More badminton.</h3><p>Share JimmiPlay with a friend, a coach or your badminton group.</p><div className="space-share">https://jimmy-xi-snowy.vercel.app/</div><button className="space-share-button" onClick={async()=>{try{await navigator.clipboard.writeText('https://jimmy-xi-snowy.vercel.app/');setMessage('Website link copied.');}catch{setMessage('Please copy the website address above.');}}}>Copy website link</button><p className="space-note">This is a general website link. Referral rewards and tracking are not active yet.</p></>}
 {page==='shop'&&<><h3>Jimmi Shop</h3><p className="space-empty">Shuttles and badminton gear. Coming soon.</p></>}
 {page==='activity'&&<><p className="space-note">Your current demo activity overview.</p><div className="space-balance"><div>Activities<strong>{stats.activities}</strong></div><div>Clubs<strong>{stats.clubs}</strong></div><div>Total hours<strong>{stats.totalHours}</strong></div><div>No-shows<strong>{stats.noShows}</strong></div></div></>}
 {message&&<p className="space-note" role="status">{message}</p>}
 </div></dialog></>;
}
